# This is a basic workflow to help you get started with Actions

name: Release-Mod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - Mod-Files/**
  pull_request:
    branches: [ main ]
    paths:
      - Mod-Files/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          # Filename for archive
          filename: 'Furry-Collection.zip'
          # Working directory before zipping
          directory: ./Mod-Files/**
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          artifacts: ./Mod-Files/Furry-Collection.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "This release is automatically generated. To view changes, check the commit history."
          tag: "Auto-Release"
